spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newssite
    username: root
    password: 
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB53Dialect
      format_sql: true
      id:
        new_generator_mappings: false