spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowCredentials: true
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
          